-- ============================================================
-- HauntLog Seed Locations — Step 2 part 2
-- ============================================================
-- Run AFTER 01-schema.sql.
-- Inserts the 26 catalog locations. Safe to re-run: ON CONFLICT
-- (id) DO UPDATE refreshes the row so you can tweak the CSV and
-- re-run while developing.
-- ============================================================

begin;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'my-haunted-manor-samuel-miller-mansion',
  'catalog',
  'My Haunted Manor USA (Samuel Miller Mansion)',
  40.0334,
  -76.5039,
  'Historic 19th-century mansion with ongoing paranormal activity. Live 24/7 cameras, public overnight ghost hunts under team guidance (filmed for series). Shared dorm cots.',
  '131 Locust St',
  'Columbia',
  'PA',
  '17512',
  'USA',
  'https://www.myhauntedmanor.com/',
  'Scheduled public overnights (check-in ~8:30pm, investigation to 2am, checkout ~11am)',
  'myhauntedmanor@gmail.com',
  NULL,
  ARRAY['18+ only','Waivers required','Equipment OK','Shared dorms','No damage']::text[],
  'https://www.myhauntedmanor.com/book-now',
  ARRAY['mansion','overnight','ghost-hunt','paranormal-investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'lizzie-borden-house',
  'catalog',
  'Lizzie Borden House',
  41.6989,
  -71.1562,
  '1892 axe murder site. Apparitions, footsteps, moving objects reported. Overnight ghost hunts and B&B stays.',
  '230 Second St',
  'Fall River',
  'MA',
  '02721',
  'USA',
  'https://lizzie-borden.com/',
  'Daily ~10am-midnight; evening hunts scheduled',
  NULL,
  '(508) 675-7333',
  ARRAY['21+ on some hunts','Equipment OK','Respect history']::text[],
  'https://lizzie-borden.com/tours/',
  ARRAY['haunted-house','overnight','axe-murder','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'villisca-axe-murder-house',
  'catalog',
  'Villisca Axe Murder House',
  40.9306,
  -94.9733,
  '1912 unsolved axe murders of 8. Designed for overnight ghost hunts.',
  '508 E 2nd St',
  'Villisca',
  'IA',
  '50864',
  'USA',
  'https://murderhouse.com/',
  'Day tours; overnights 5pm-10am',
  'contact@murderhouse.com',
  '(712) 250-5122',
  ARRAY['Equipment rental available','Max 12 guests','No damage']::text[],
  'https://murderhouse.com/overnight-stay/',
  ARRAY['haunted-house','overnight','axe-murder','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'the-stanley-hotel',
  'catalog',
  'The Stanley Hotel',
  40.3829,
  -105.5192,
  'Inspired Stephen King''s The Shining. Ghosts, music, apparitions. Ghost tours and overnight investigations.',
  '333 Wonderview Ave',
  'Estes Park',
  'CO',
  '80517',
  'USA',
  'https://www.stanleyhotel.com/',
  'Daily tours; hotel open 24/7',
  'live@stanleyhotel.com',
  '(970) 577-4000',
  ARRAY['Age varies by event','Equipment on event nights']::text[],
  'https://www.stanleyhotel.com/activities/hotel-tours',
  ARRAY['hotel','ghost-tour','shining-inspired','paranormal']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'rms-queen-mary',
  'catalog',
  'RMS Queen Mary',
  33.7526,
  -118.1905,
  'WWII deaths and haunted staterooms (B340). Paranormal tours and overnight stays.',
  '1126 Queens Hwy',
  'Long Beach',
  'CA',
  '90802',
  'USA',
  'https://www.queenmary.com/',
  'Daily tours; scheduled paranormal events',
  NULL,
  '(562) 435-3511',
  ARRAY['Guided','Closed shoes required']::text[],
  'https://www.queenmary.com/paranormal-attractions.htm',
  ARRAY['ship','haunted-ship','paranormal-tour','overnight']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'trans-allegheny-lunatic-asylum',
  'catalog',
  'Trans-Allegheny Lunatic Asylum',
  39.038,
  -80.467,
  '19th-century asylum. Shadow figures and disembodied screams reported. Year-round hunts.',
  '71 Asylum Dr',
  'Weston',
  'WV',
  '26452',
  'USA',
  'https://trans-alleghenylunaticasylum.com/',
  'Evening and overnight hunts scheduled',
  'info@trans-alleghenylunaticasylum.com',
  '(304) 269-5070',
  ARRAY['12+','Equipment OK']::text[],
  'https://trans-alleghenylunaticasylum.com/schedule-of-events/',
  ARRAY['asylum','overnight','ghost-hunt','paranormal']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'waverly-hills-sanatorium',
  'catalog',
  'Waverly Hills Sanatorium',
  38.130291,
  -85.841243,
  'Former TB hospital. Body chute and apparitions. Tours and overnight investigations.',
  '4400 Paralee Dr',
  'Louisville',
  'KY',
  '40272',
  'USA',
  'https://www.thewaverlyhillssanatorium.com/',
  'Scheduled hunts',
  NULL,
  '(502) 690-7880',
  ARRAY['Equipment allowed on investigations']::text[],
  NULL,
  ARRAY['asylum','tb-hospital','paranormal-investigation','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'eastern-state-penitentiary',
  'catalog',
  'Eastern State Penitentiary',
  39.9683,
  -75.1725,
  '1829 prison. Shadows and voices reported. Tours; limited investigations.',
  '2027 Fairmount Ave',
  'Philadelphia',
  'PA',
  '19130',
  'USA',
  'https://easternstate.org/',
  '~10am-5pm seasonal',
  'info@easternstate.org',
  '(215) 236-3300',
  ARRAY['No equipment on basic tours']::text[],
  'https://easternstate.org/tickets',
  ARRAY['prison','ghost-tour','penitentiary','limited-investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'myrtles-plantation',
  'catalog',
  'Myrtles Plantation',
  30.753,
  -91.385,
  'Antebellum plantation. "Mirror of Death" and Chloe ghost legends. Mystery tours and overnight stays.',
  '7747 US Hwy 61',
  'St. Francisville',
  'LA',
  '70775',
  'USA',
  'https://www.themyrtles.com/',
  'Daily tours; B&B 24/7',
  'reservations@themyrtles.com',
  '(225) 635-6277',
  ARRAY['Overnight guests may investigate']::text[],
  'https://www.themyrtles.com/',
  ARRAY['plantation','overnight','mystery-tour','ghost']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'ohio-state-reformatory',
  'catalog',
  'Ohio State Reformatory',
  40.7838,
  -82.5017,
  'The Shawshank prison. Apparitions and EVPs reported. Ghost hunts and investigations.',
  '100 Reformatory Rd',
  'Mansfield',
  'OH',
  '44905',
  'USA',
  'https://www.mrps.org/',
  'Evening and overnight programs scheduled',
  'kathy@mrps.org',
  '(419) 522-2644',
  ARRAY['18+','Equipment OK']::text[],
  'https://www.mrps.org/paranormal-programs/',
  ARRAY['prison','overnight','shawshank','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'pennhurst-state-school-and-asylum',
  'catalog',
  'Pennhurst State School & Asylum',
  40.1937,
  -75.5602,
  'Infamous institution with documented abuse history. Overnight investigations.',
  '601 N Church St',
  'Spring City',
  'PA',
  '19475',
  'USA',
  'https://pennhurstasylum.com/',
  '7pm-2/3am overnights',
  NULL,
  '(484) 886-6080',
  ARRAY['18+','Equipment OK']::text[],
  'http://secure.interactiveticketing.com/1.43/ec53d5/',
  ARRAY['asylum','overnight','investigation','paranormal']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'crescent-hotel-and-spa',
  'catalog',
  'Crescent Hotel & Spa',
  36.4083,
  -93.7372,
  'America''s Most Haunted Hotel. Morgue, spirits, lockdowns and investigations.',
  '75 Prospect Ave',
  'Eureka Springs',
  'AR',
  '72632',
  'USA',
  'https://crescent-hotel.com/',
  'Nightly ghost tours from 7pm',
  'reserveeureka@gmail.com',
  '(479) 253-9766',
  ARRAY['Guided','Equipment on event nights']::text[],
  'https://www.reserveeureka.com/attractions/crescentghost',
  ARRAY['hotel','most-haunted','overnight','ghost-tour']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'whaley-house',
  'catalog',
  'Whaley House',
  32.7527,
  -117.1945,
  'Called America''s Most Haunted House. Evening tours and after-hours investigations.',
  '2476 San Diego Ave',
  'San Diego',
  'CA',
  '92110',
  'USA',
  'https://www.whaleyhousesandiego.com/',
  'Day 10am-5pm; evening paranormal events',
  'WhaleyHouse@historictours.com',
  '(619) 273-5824',
  ARRAY['Equipment on investigations']::text[],
  'https://www.whaleyhousesandiego.com/san-diego-paranormal-investigation-tickets/',
  ARRAY['haunted-house','after-hours','paranormal-investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'uss-hornet',
  'catalog',
  'USS Hornet',
  37.772,
  -122.302,
  'WWII aircraft carrier. Overnights and private paranormal investigations.',
  '707 W Hornet Ave',
  'Alameda',
  'CA',
  '94501',
  'USA',
  'https://uss-hornet.org/',
  'Scheduled paranormal events',
  'info@uss-hornet.org',
  '(510) 521-8448',
  ARRAY['Guided or private','Waivers required']::text[],
  'https://uss-hornet.org/program-types/paranormal/',
  ARRAY['ship','overnight','wwii','paranormal']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'brushy-mountain-state-penitentiary',
  'catalog',
  'Brushy Mountain State Penitentiary',
  36.11,
  -84.442,
  'Violent prison history. 4-hour and overnight investigations.',
  '9182 Hwy 116',
  'Petros',
  'TN',
  '37845',
  'USA',
  'https://tourbrushy.com/',
  'Evening and overnight (10pm start)',
  NULL,
  '(423) 324-8687',
  ARRAY['Guided','Equipment OK']::text[],
  'https://tourbrushy.com/',
  ARRAY['prison','overnight','violent-history','ghost-investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'rolling-hills-asylum',
  'catalog',
  'Rolling Hills Asylum',
  42.881,
  -78.133,
  'Former poor farm and asylum. Public and private hunts.',
  '11001 Bethany Center Rd',
  'East Bethany',
  'NY',
  '14054',
  'USA',
  'https://rollinghillsasylum.com/',
  'Scheduled evening hunts',
  NULL,
  '(585) 502-4066',
  ARRAY['Waivers per event']::text[],
  'https://rollinghillsasylum.com/',
  ARRAY['asylum','poor-farm','public-hunt','private-investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'west-virginia-penitentiary-moundsville',
  'catalog',
  'West Virginia Penitentiary (Moundsville)',
  39.916,
  -80.742,
  'Gothic prison; executions and riots. Public ghost hunts.',
  '818 Jefferson Ave',
  'Moundsville',
  'WV',
  '26041',
  'USA',
  'https://wvpentours.com/',
  'Evening hunts scheduled',
  NULL,
  '(304) 845-6200',
  ARRAY['18+ typical']::text[],
  'https://wvpentours.com/',
  ARRAY['prison','gothic','executions','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'battleship-north-carolina',
  'catalog',
  'Battleship North Carolina',
  34.236,
  -77.954,
  'WWII battleship. Sailor deaths and overnight hunts.',
  '1 Battleship Rd',
  'Wilmington',
  'NC',
  '28401',
  'USA',
  NULL,
  'Scheduled overnights via partners',
  NULL,
  NULL,
  ARRAY['Group events','Equipment OK']::text[],
  'https://www.hauntedrooms.com/north-carolina/ghost-hunts/battleship-north-carolina-wilmington',
  ARRAY['ship','overnight','wwii','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'jennie-wade-house-gettysburg',
  'catalog',
  'Jennie Wade House',
  39.83,
  -77.231,
  'Civil War civilian death site. Overnight hunts via US Ghost Adventures.',
  '548 Baltimore St',
  'Gettysburg',
  'PA',
  '17325',
  'USA',
  NULL,
  'Evenings and overnights scheduled',
  NULL,
  NULL,
  ARRAY['Guided','Respect site']::text[],
  'https://usghostadventures.com/haunted-houses/jennie-wade-birthplace/',
  ARRAY['haunted-house','civil-war','overnight','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'fort-mifflin',
  'catalog',
  'Fort Mifflin',
  39.876,
  -75.208,
  'Revolutionary War fort. Casemate investigations.',
  '6400 Hog Island Rd',
  'Philadelphia',
  'PA',
  '19153',
  'USA',
  'https://fortmifflin.us/',
  'Scheduled events',
  'fortmifflininfo@gmail.com',
  '(856) 831-5690',
  ARRAY['Equipment OK','Weather dependent']::text[],
  'https://fortmifflin.us/',
  ARRAY['fort','revolutionary-war','investigation','paranormal']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'missouri-state-penitentiary',
  'catalog',
  'Missouri State Penitentiary',
  38.572,
  -92.168,
  'Oldest prison west of the Mississippi (until 2004). 3-hour hunts and overnights.',
  '115 Lafayette St',
  'Jefferson City',
  'MO',
  '65101',
  'USA',
  'https://missouripentours.com/',
  'Scheduled hunts and overnights',
  'info@missouripentours.com',
  '(573) 632-3999',
  ARRAY['Age restrictions vary by event']::text[],
  'https://missouripentours.com/',
  ARRAY['prison','oldest-prison','overnight','ghost-hunt']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'lemp-mansion',
  'catalog',
  'Lemp Mansion',
  38.615,
  -90.209,
  'Famous for suicides and hauntings. Restaurant with ghost tours and paranormal events.',
  '3322 De Menil Pl',
  'St. Louis',
  'MO',
  '63118',
  'USA',
  'https://lempmansion.com/',
  'Dinner and tours; paranormal events scheduled',
  NULL,
  '(314) 664-8024',
  ARRAY['Guided mostly','Check for investigation nights']::text[],
  'https://lempmansion.com/',
  ARRAY['mansion','suicide-hauntings','ghost-tour','restaurant']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'berkeley-plantation',
  'catalog',
  'Berkeley Plantation',
  37.322,
  -77.175,
  'Colonial plantation. Civil War ghosts. Public ghost hunts via partners.',
  '12602 Harrison Landing Rd',
  'Charles City',
  'VA',
  '23030',
  'USA',
  NULL,
  'Scheduled hunts via partners',
  NULL,
  NULL,
  ARRAY['Group events']::text[],
  'https://www.hauntedrooms.com/virginia/ghost-hunts/berkeley-plantation',
  ARRAY['plantation','civil-war','ghost-hunt','public']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'historic-palmyra-ghost-hunt',
  'catalog',
  'Historic Palmyra Ghost Hunt',
  43.064,
  -77.234,
  'Historic village with multiple haunted buildings. Full ghost hunts.',
  'Downtown',
  'Palmyra',
  'NY',
  '14522',
  'USA',
  NULL,
  'Evenings and overnight via partners',
  NULL,
  NULL,
  ARRAY['Equipment allowed']::text[],
  'https://www.hauntedrooms.com/new-york/ghost-hunts/historic-palmyra',
  ARRAY['village','multiple-buildings','ghost-hunt','overnight']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'whispers-estate',
  'catalog',
  'Whispers Estate',
  38.733,
  -86.46,
  'Victorian mansion with child-spirit reports and reported activity. Overnight hunts.',
  '410 Main St',
  'Mitchell',
  'IN',
  '47446',
  'USA',
  NULL,
  'Scheduled nights via partners',
  NULL,
  NULL,
  ARRAY['18+','Waivers required']::text[],
  NULL,
  ARRAY['mansion','victorian','child-spirits','overnight']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

insert into locations (id, source, name, lat, lng, description, street, city, state, zip, country, website, hours, contact_email, contact_phone, rules, booking_url, tags, created_by_handle) values (
  'landolls-mohican-castle',
  'catalog',
  'Landoll''s Mohican Castle',
  40.612,
  -82.233,
  'Stone castle with haunted cottages. Ghost walks and investigations.',
  '5611 SR 3',
  'Loudonville',
  'OH',
  '44842',
  'USA',
  'https://landollsmohicancastle.com/ghosthunts/',
  'Scheduled paranormal events',
  NULL,
  '(419) 994-3427',
  ARRAY['Guided or private']::text[],
  'https://landollsmohicancastle.com/ghosthunts/',
  ARRAY['castle','haunted-cottages','ghost-walk','investigation']::text[],
  '@hauntlog'
) on conflict (id) do update set
  source = excluded.source,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  street = excluded.street,
  city = excluded.city,
  state = excluded.state,
  zip = excluded.zip,
  country = excluded.country,
  website = excluded.website,
  hours = excluded.hours,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  rules = excluded.rules,
  booking_url = excluded.booking_url,
  tags = excluded.tags;

commit;

-- Verify: should return 26
-- select count(*) from locations where source = 'catalog';
